name: SSH Deploy Workflow
description: Deploys the project to a remote server via SSH using rsync.
env:
  VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
  WEBSITE_FOLDER: 'your-website-folder' # Replace with your actual website folder name

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Install node dependencies
        run: npm ci
      - name: Setup Project
        env:
          VITE_API_BASE_URL: ${{ vars.VITE_API_BASE_URL }}
        run: |
          npm run build
      - name: Delete old build files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo find /var/www/${{ vars.WEBSITE_FOLDER }} -mindepth 1 ! -name '.htaccess' -delete
      - name: Install SSH key inside action runner
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Copy Build Files to Target Server
        run: |
          rsync -r -e "ssh -p ${{ secrets.SSH_PORT }}" ${{ github.workspace }}/dist/ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/var/www/${{ vars.WEBSITE_FOLDER }}/